<?php
/**
 * Error messages etc
 */
define("ERROR_ACCESS_DENIED", "ERROR_ACCESS_DENIED");
define("ERROR_INVALID_PARAMETERS", "ERROR_INVALID_PARAMETERS");
define("ERROR_INTERNAL_DATABASE", "ERROR_INTERNAL_DATABASE");
define("ERROR_PROJECT_NOT_FOUND", "ERROR_PROJECT_NOT_FOUND");
define("ERROR_INVALID_ACTION", "ERROR_INVALID_ACTION");
define("ERROR_ACTION_NOT_PERMITTED", "ERROR_ACTION_NOT_PERMITTED");
define("ERROR_FEATURE_NOT_IMPLEMENTED", "ERROR_FEATURE_NOT_IMPLEMENTED");
define("ERROR_CONVERSION_FAILURE", "ERROR_CONVERSION_FAILURE");
?>
